version: 1.0.{build}
os: Windows Server 2012 R2
clone_depth: 8
clone_folder: C:\w\
build:
  verbosity: detailed
environment:
  BINTRAY_USER:
    secure: jfLq1ApyVLNouxv07skhrg==
  BINTRAY_APIKEY:
    secure: Awq2bXuEyT0/JC/phuGILqT9hj9sVslq2+btJlFhH89a1xagztNH8h3jTru5rJKd
  GPG_PASSPHRASE:
    secure: t0zZqLgvaePWqUGn/dLMQ50M3YkMTktXSWglL1dyaEHKTOuXYiNe070dNlJEAoi1
  VIRUSTOTAL_APIKEY:
    secure: TdJYONfrpH45DuyKxraVqgHYy25IQ/F8TKHzYf+u5zz1aiM2yR0YTMaGxyj2EMReEearSI9kD9D2ZykybSVEbRyEaotZlceUb2lPDKELl3M=
build_script:
  - set PATH=C:\Python27-x64;C:\msys64\usr\bin;%SystemRoot%\system32
  - pacman --noconfirm --noprogressbar -S --needed mc
  - pacman --noconfirm --noprogressbar -S -yu -u
  - pacman --noconfirm --noprogressbar -S -yu -u
  - pacman --noconfirm --noprogressbar -S --needed p7zip mingw-w64-{i686,x86_64}-jq
  - sh -c ./_build.sh
artifacts:
  - path: '*-*-mingw.*'
    name: master
  - path: '*-*-mingw-libressl.*'
    name: master-libressl
  - path: 'all-mingw.*'
    name: all
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
